version: "3.9"

services:
  eraven:
    image: ${DOCKER_REGISTRY-}eraven
    build:
      context: .
      dockerfile: src/eRaven/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=eraven;Username=postgres;Password=postgres"
      TZ: Europe/Kyiv
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/"]
      interval: 10s
      timeout: 3s
      retries: 10

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: eraven
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Kyiv
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eraven || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"

volumes:
  pgdata:
