// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eRaven.Infrastructure;

#nullable disable

namespace eRaven.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225113104_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eRaven.Domain.Entities.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ClosedAt")
                        .HasColumnType("date")
                        .HasColumnName("closed_at");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<int>("MissionMode")
                        .HasColumnType("integer")
                        .HasColumnName("mission_mode");

                    b.Property<string>("NamePoint")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("name_point");

                    b.Property<string>("PositionArea")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("position_area");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target");

                    b.Property<string>("TypeDrone")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type_drone");

                    b.HasKey("Id");

                    b.HasIndex("MissionMode")
                        .HasDatabaseName("ix_missions_mode");

                    b.HasIndex("PositionArea")
                        .HasDatabaseName("ix_missions_position_area");

                    b.HasIndex("PositionArea", "CreatedAt", "ClosedAt")
                        .HasDatabaseName("ix_missions_area_created_closed");

                    b.HasIndex("PositionArea", "NamePoint", "MissionMode", "Target")
                        .IsUnique()
                        .HasDatabaseName("ux_missions_active_key")
                        .HasFilter("\"closed_at\" IS NULL");

                    b.ToTable("missions", null, t =>
                        {
                            t.HasCheckConstraint("ck_missions_dates", "\"closed_at\" IS NULL OR \"closed_at\" >= \"created_at\"");
                        });
                });

            modelBuilder.Entity("eRaven.Domain.Entities.PersonEventRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("author");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("EventId");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_person_events_event_type");

                    b.HasIndex("AggregateId", "EffectiveDate")
                        .HasDatabaseName("ix_person_events_aggregate_effective_date");

                    b.HasIndex("AggregateId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_person_events_aggregate_version");

                    b.ToTable("person_events", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.PersonReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bzvp")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bzvp");

                    b.Property<string>("Callsign")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("callsign");

                    b.Property<DateOnly?>("EnrolledAt")
                        .HasColumnType("date")
                        .HasColumnName("enrolled_at");

                    b.Property<int?>("EnrollmentKind")
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_kind");

                    b.Property<string>("EnrollmentReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("enrollment_reference");

                    b.Property<DateOnly?>("ExcludedAt")
                        .HasColumnType("date")
                        .HasColumnName("excluded_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("full_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Position")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("position");

                    b.Property<int?>("PositionSort")
                        .HasColumnType("integer")
                        .HasColumnName("position_sort");

                    b.Property<string>("Rank")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("rank");

                    b.Property<string>("Rnokpp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rnokpp");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("Weapon")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("weapon");

                    b.HasKey("Id");

                    b.HasIndex("Lifecycle")
                        .HasDatabaseName("ix_person_read_lifecycle");

                    b.HasIndex("Rnokpp")
                        .IsUnique()
                        .HasDatabaseName("ux_person_read_rnokpp");

                    b.HasIndex("EnrolledAt", "ExcludedAt")
                        .HasDatabaseName("ix_person_read_enrolled_excluded");

                    b.HasIndex("EnrollmentKind", "PositionSort", "LastName")
                        .HasDatabaseName("ix_person_read_kind_possort_last");

                    b.ToTable("person_read", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetCodeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_terminal");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<byte>("RoleCode")
                        .HasColumnType("smallint")
                        .HasColumnName("role_code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<byte>("UiStyle")
                        .HasColumnType("smallint")
                        .HasColumnName("ui_style");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_timesheet_codes_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_timesheet_codes_active");

                    b.ToTable("timesheet_codes", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetCodeTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FromCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_code_id");

                    b.Property<int>("StartShiftDays")
                        .HasColumnType("integer")
                        .HasColumnName("start_shift_days");

                    b.Property<Guid>("ToCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_code_id");

                    b.HasKey("Id");

                    b.HasIndex("ToCodeId");

                    b.HasIndex("FromCodeId", "ToCodeId")
                        .IsUnique()
                        .HasDatabaseName("ux_timesheet_code_transitions_from_to");

                    b.ToTable("timesheet_code_transitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_timesheet_code_transitions_start_shift_days", "\"start_shift_days\" IN (0,1)");
                        });
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetCodeTransition", b =>
                {
                    b.HasOne("eRaven.Domain.Entities.TimesheetCodeDefinition", "FromCode")
                        .WithMany()
                        .HasForeignKey("FromCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eRaven.Domain.Entities.TimesheetCodeDefinition", "ToCode")
                        .WithMany()
                        .HasForeignKey("ToCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromCode");

                    b.Navigation("ToCode");
                });
#pragma warning restore 612, 618
        }
    }
}
