// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eRaven.Infrastructure;

#nullable disable

namespace eRaven.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215202159_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eRaven.Domain.Aggregates.TimeSheetAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ClosedAt")
                        .HasColumnType("date")
                        .HasColumnName("closed_at");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("closed_by");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("OpenedAt")
                        .HasColumnType("date")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ux_ts_aggregates_person_active")
                        .HasFilter("closed_at IS NULL");

                    b.HasIndex("PersonId", "ClosedAt")
                        .HasDatabaseName("ix_ts_aggregates_person_closed");

                    b.HasIndex("PersonId", "OpenedAt")
                        .HasDatabaseName("ix_ts_aggregates_person_opened");

                    b.ToTable("timesheet_aggregates", null, t =>
                        {
                            t.HasCheckConstraint("ck_ts_aggregates_closed_gte_opened", "closed_at IS NULL OR closed_at >= opened_at");
                        });
                });

            modelBuilder.Entity("eRaven.Domain.Entities.CombatTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CombatTaskDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("combat_task_document_id");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mission_id");

                    b.Property<string>("SourceDocument")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sourge_document");

                    b.HasKey("Id");

                    b.HasIndex("CombatTaskDocumentId");

                    b.HasIndex("MissionId");

                    b.ToTable("combat_tasks", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.CombatTaskDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Callsign")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("callsign");

                    b.Property<Guid>("CombatTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("combat_task_id");

                    b.Property<DateOnly>("EffectiveAt")
                        .HasColumnType("date")
                        .HasColumnName("effective_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("full_name");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Rnokpp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rnokpp");

                    b.HasKey("Id");

                    b.HasIndex("CombatTaskId");

                    b.HasIndex("Kind");

                    b.HasIndex("PersonId", "EffectiveAt");

                    b.HasIndex("CombatTaskId", "PersonId", "Kind", "EffectiveAt")
                        .IsUnique();

                    b.ToTable("combat_task_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_combat_task_lines_kind_valid", "kind IN (1, 2)");
                        });
                });

            modelBuilder.Entity("eRaven.Domain.Entities.CombatTaskDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CanceledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceled_at_utc");

                    b.Property<string>("CanceledBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("canceled_by");

                    b.Property<string>("CanceledReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("canceled_reason");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("OrderTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("order_title");

                    b.Property<DateOnly>("RecordedAt")
                        .HasColumnType("date")
                        .HasColumnName("recorded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("OrderTitle")
                        .IsUnique();

                    b.HasIndex("RecordedAt");

                    b.HasIndex("Status");

                    b.ToTable("combat_task_documents", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ClosedAt")
                        .HasColumnType("date")
                        .HasColumnName("closed_at");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<int>("MissionMode")
                        .HasColumnType("integer")
                        .HasColumnName("mission_mode");

                    b.Property<string>("NamePoint")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasDefaultValue("")
                        .HasColumnName("name_point");

                    b.Property<string>("PositionArea")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("position_area");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TypeDrone")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type_drone");

                    b.HasKey("Id");

                    b.HasIndex("MissionMode");

                    b.HasIndex("PositionArea");

                    b.HasIndex("PositionArea", "CreatedAt", "ClosedAt");

                    b.HasIndex("PositionArea", "NamePoint", "MissionMode", "Target")
                        .IsUnique()
                        .HasFilter("\"closed_at\" IS NULL");

                    b.ToTable("missions", null, t =>
                        {
                            t.HasCheckConstraint("ck_missions_dates", "\"closed_at\" IS NULL OR \"closed_at\" >= \"created_at\"");
                        });
                });

            modelBuilder.Entity("eRaven.Domain.Entities.MissionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClosedByDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_document_id");

                    b.Property<Guid>("CombatTaskDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("combat_task_document_id");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mission_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateOnly?>("To")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.HasKey("Id");

                    b.HasIndex("CombatTaskDocumentId", "MissionId", "PersonId")
                        .IsUnique()
                        .HasFilter("to_date IS NULL");

                    b.HasIndex("MissionId", "From", "To");

                    b.HasIndex("PersonId", "From", "To");

                    b.ToTable("mission_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_mission_assignments_to_gte_from", "to_date IS NULL OR to_date >= from_date");
                        });
                });

            modelBuilder.Entity("eRaven.Domain.Entities.PersonEventRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("author");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("EventId");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_person_events_event_type");

                    b.HasIndex("AggregateId", "EffectiveDate")
                        .HasDatabaseName("ix_person_events_aggregate_effective_date");

                    b.HasIndex("AggregateId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_person_events_aggregate_version");

                    b.ToTable("person_events", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.PersonReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bzvp")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bzvp");

                    b.Property<string>("Callsign")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("callsign");

                    b.Property<DateOnly?>("EnrolledAt")
                        .HasColumnType("date")
                        .HasColumnName("enrolled_at");

                    b.Property<int?>("EnrollmentKind")
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_kind");

                    b.Property<string>("EnrollmentReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("enrollment_reference");

                    b.Property<DateOnly?>("ExcludedAt")
                        .HasColumnType("date")
                        .HasColumnName("excluded_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("full_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Position")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("position");

                    b.Property<int?>("PositionSort")
                        .HasColumnType("integer")
                        .HasColumnName("position_sort");

                    b.Property<string>("Rank")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("rank");

                    b.Property<string>("Rnokpp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rnokpp");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("Weapon")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("weapon");

                    b.HasKey("Id");

                    b.HasIndex("Lifecycle")
                        .HasDatabaseName("ix_person_read_lifecycle");

                    b.HasIndex("Rnokpp")
                        .IsUnique()
                        .HasDatabaseName("ux_person_read_rnokpp");

                    b.HasIndex("EnrolledAt", "ExcludedAt")
                        .HasDatabaseName("ix_person_read_enrolled_excluded");

                    b.HasIndex("EnrollmentKind", "PositionSort", "LastName")
                        .HasDatabaseName("ix_person_read_kind_possort_last");

                    b.ToTable("person_read", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetCodeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("timesheet_codes", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetCodeTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FromCodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartShiftDays")
                        .HasColumnType("integer")
                        .HasColumnName("start_shift_days");

                    b.Property<Guid>("ToCodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ToCodeId");

                    b.HasIndex("FromCodeId", "ToCodeId")
                        .IsUnique();

                    b.ToTable("timesheet_code_ttransitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_timesheet_code_ttransitions_start_shift_days", "\"start_shift_days\" IN (0,1)");
                        });
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("DeleteReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("delete_reason");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("deleted_by");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reference");

                    b.Property<Guid?>("TimeSheetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimesheetCodeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("timesheet_codedefinition_id");

                    b.Property<Guid>("TimesheetId")
                        .HasColumnType("uuid")
                        .HasColumnName("timesheet_id");

                    b.Property<DateOnly?>("To")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TimeSheetId");

                    b.HasIndex("TimesheetCodeDefinitionId");

                    b.HasIndex("TimesheetId", "From")
                        .HasDatabaseName("ix_ts_entries_timesheet_from");

                    b.HasIndex("PersonId", "From", "To")
                        .HasDatabaseName("ix_ts_entries_person_range");

                    b.ToTable("timesheet_entries", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetTaskSpan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClosedByCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_code_id");

                    b.Property<string>("ClosedReference")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("closed_reference");

                    b.Property<Guid>("CombatTaskDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("combat_task_document_id");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mission_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TimesheetId")
                        .HasColumnType("uuid")
                        .HasColumnName("timesheet_id");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetId");

                    b.HasIndex("CombatTaskDocumentId", "Status");

                    b.HasIndex("PersonId", "CombatTaskDocumentId", "MissionId")
                        .IsUnique();

                    b.HasIndex("PersonId", "FromDate", "ToDate");

                    b.HasIndex("MissionId", "FromDate", "ToDate", "Status");

                    b.ToTable("timesheet_task_spans", null, t =>
                        {
                            t.HasCheckConstraint("ck_ts_task_spans_to_gte_from", "to_date IS NULL OR to_date >= from_date");
                        });
                });

            modelBuilder.Entity("eRaven.Domain.Entities.CombatTask", b =>
                {
                    b.HasOne("eRaven.Domain.Entities.CombatTaskDocument", "CombatTaskDocument")
                        .WithMany("CombatTasks")
                        .HasForeignKey("CombatTaskDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRaven.Domain.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CombatTaskDocument");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("eRaven.Domain.Entities.CombatTaskDetails", b =>
                {
                    b.HasOne("eRaven.Domain.Entities.CombatTask", "CombatTask")
                        .WithMany("CombatTaskDetails")
                        .HasForeignKey("CombatTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CombatTask");
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetCodeTransition", b =>
                {
                    b.HasOne("eRaven.Domain.Entities.TimesheetCodeDefinition", "FromCode")
                        .WithMany()
                        .HasForeignKey("FromCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eRaven.Domain.Entities.TimesheetCodeDefinition", "ToCode")
                        .WithMany()
                        .HasForeignKey("ToCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromCode");

                    b.Navigation("ToCode");
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetEntry", b =>
                {
                    b.HasOne("eRaven.Domain.Aggregates.TimeSheetAggregate", "TimeSheet")
                        .WithMany()
                        .HasForeignKey("TimeSheetId");

                    b.HasOne("eRaven.Domain.Entities.TimesheetCodeDefinition", "TimesheetCodeDefinition")
                        .WithMany()
                        .HasForeignKey("TimesheetCodeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eRaven.Domain.Aggregates.TimeSheetAggregate", null)
                        .WithMany("Entries")
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeSheet");

                    b.Navigation("TimesheetCodeDefinition");
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetTaskSpan", b =>
                {
                    b.HasOne("eRaven.Domain.Aggregates.TimeSheetAggregate", null)
                        .WithMany("TaskSpans")
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eRaven.Domain.Aggregates.TimeSheetAggregate", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("TaskSpans");
                });

            modelBuilder.Entity("eRaven.Domain.Entities.CombatTask", b =>
                {
                    b.Navigation("CombatTaskDetails");
                });

            modelBuilder.Entity("eRaven.Domain.Entities.CombatTaskDocument", b =>
                {
                    b.Navigation("CombatTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
