// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eRaven.Infrastructure;

#nullable disable

namespace eRaven.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260122211011_UpTimesheetCodeDefinition")]
    partial class UpTimesheetCodeDefinition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eRaven.Domain.Entities.MonthlyTimesheetReadModel", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("PersonId", "Year", "Month");

                    b.ToTable("monthly_timesheets", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.PersonEventRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("author");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("EventId");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_person_events_event_type");

                    b.HasIndex("AggregateId", "EffectiveDate")
                        .HasDatabaseName("ix_person_events_aggregate_effective_date");

                    b.HasIndex("AggregateId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_person_events_aggregate_version");

                    b.ToTable("person_events", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.PersonReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bzvp")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bzvp");

                    b.Property<string>("Callsign")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("callsign");

                    b.Property<DateOnly?>("EnrolledAt")
                        .HasColumnType("date")
                        .HasColumnName("enrolled_at");

                    b.Property<int?>("EnrollmentKind")
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_kind");

                    b.Property<string>("EnrollmentReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("enrollment_reference");

                    b.Property<DateOnly?>("ExcludedAt")
                        .HasColumnType("date")
                        .HasColumnName("excluded_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("full_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Position")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("position");

                    b.Property<int?>("PositionSort")
                        .HasColumnType("integer")
                        .HasColumnName("position_sort");

                    b.Property<string>("Rank")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("rank");

                    b.Property<string>("Rnokpp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rnokpp");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("Weapon")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("weapon");

                    b.HasKey("Id");

                    b.HasIndex("Lifecycle")
                        .HasDatabaseName("ix_person_read_lifecycle");

                    b.HasIndex("Rnokpp")
                        .IsUnique()
                        .HasDatabaseName("ux_person_read_rnokpp");

                    b.HasIndex("EnrolledAt", "ExcludedAt")
                        .HasDatabaseName("ix_person_read_enrolled_excluded");

                    b.HasIndex("EnrollmentKind", "PositionSort", "LastName")
                        .HasDatabaseName("ix_person_read_kind_possort_last");

                    b.ToTable("person_read", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetCodeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<int>("EndDateMeaning")
                        .HasColumnType("integer")
                        .HasColumnName("end_date_meaning");

                    b.Property<int>("EndMode")
                        .HasColumnType("integer")
                        .HasColumnName("end_mode");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPlanningCutoff")
                        .HasColumnType("boolean")
                        .HasColumnName("is_planning_cutoff");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_terminal");

                    b.Property<int>("Lane")
                        .HasColumnType("integer")
                        .HasColumnName("lane");

                    b.Property<string>("NextCodeOnEnd")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("next_code_on_end");

                    b.Property<int>("PlanningCutoffShiftDays")
                        .HasColumnType("integer")
                        .HasColumnName("planning_cutoff_shift_days");

                    b.Property<bool>("RequiresNote")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_note");

                    b.Property<bool>("RequiresReference")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_reference");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Lane", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_ts_codes_lane_code");

                    b.ToTable("timesheet_codes", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetCodeTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FromCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_code_id");

                    b.Property<int>("Lane")
                        .HasColumnType("integer")
                        .HasColumnName("lane");

                    b.Property<Guid>("ToCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_code_id");

                    b.HasKey("Id");

                    b.HasIndex("ToCodeId");

                    b.HasIndex("FromCodeId", "ToCodeId")
                        .IsUnique()
                        .HasDatabaseName("ux_ts_transitions_from_to");

                    b.HasIndex("Lane", "FromCodeId")
                        .HasDatabaseName("ix_ts_transitions_lane_from");

                    b.ToTable("timesheet_code_transitions", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("DeleteReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("delete_reason");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("deleted_by");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date")
                        .HasColumnName("from");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Lane")
                        .HasColumnType("integer")
                        .HasColumnName("lane");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("note");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference");

                    b.Property<DateOnly?>("To")
                        .HasColumnType("date")
                        .HasColumnName("to");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "IsDeleted")
                        .HasDatabaseName("ix_ts_entry_person_deleted");

                    b.HasIndex("PersonId", "Lane", "From")
                        .HasDatabaseName("ix_ts_entry_person_lane_from");

                    b.HasIndex("PersonId", "Lane", "To")
                        .HasDatabaseName("ix_ts_entry_person_lane_to");

                    b.ToTable("Timesheet_entries", (string)null);
                });

            modelBuilder.Entity("eRaven.Domain.Entities.MonthlyTimesheetReadModel", b =>
                {
                    b.OwnsMany("eRaven.Domain.Entities.MonthlyTimesheetDay", "Days", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Year")
                                .HasColumnType("integer");

                            b1.Property<int>("Month")
                                .HasColumnType("integer");

                            b1.Property<int>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("day");

                            b1.Property<int>("Lane")
                                .HasColumnType("integer");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid?>("EntryId")
                                .HasColumnType("uuid");

                            b1.HasKey("PersonId", "Year", "Month", "Day", "Lane");

                            b1.HasIndex("PersonId", "Year", "Month");

                            b1.ToTable("monthly_timesheet_days", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PersonId", "Year", "Month");
                        });

                    b.Navigation("Days");
                });

            modelBuilder.Entity("eRaven.Domain.Entities.TimesheetCodeTransition", b =>
                {
                    b.HasOne("eRaven.Domain.Entities.TimesheetCodeDefinition", "FromCode")
                        .WithMany()
                        .HasForeignKey("FromCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eRaven.Domain.Entities.TimesheetCodeDefinition", "ToCode")
                        .WithMany()
                        .HasForeignKey("ToCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromCode");

                    b.Navigation("ToCode");
                });
#pragma warning restore 612, 618
        }
    }
}
